Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/ubuntu/workspace/elections/views.py", line 21, in index
    return render(request, 'elections/index.html', context)
  File "/usr/local/lib/python2.7/dist-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/usr/local/lib/python2.7/dist-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/defaulttags.py", line 173, in render
    len_values = len(values)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 232, in __len__
    self._fetch_all()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 1105, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 886, in execute_sql
    raise original_exception
ProgrammingError: (1146, "Table 'c9.elections_product' doesn't exist")
[28/Jun/2017 16:25:12] "GET / HTTP/1.1" 500 137039
Internal Server Error: /admin/elections/product/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/options.py", line 551, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/sites.py", line 224, in inner
    return view(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/options.py", line 1542, in changelist_view
    self.list_max_show_all, self.list_editable, self,
  File "/usr/local/lib/python2Error: That port is already in use.
n/views/main.py", line 79, in __init__
    self.get_results(request)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/views/main.py", line 177, in get_results
    result_count = paginator.count
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/django/core/paginator.py", line 79, in count
    return self.object_list.count()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 364, in count
    return self.query.get_count(using=self.db)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py", line 499, in get_count
    number = obj.get_aggregation(using, ['__count'])['__count']
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py", line 480, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 886, in execute_sql
    raise original_exception
ProgrammingError: (1146, "Table 'c9.elections_product' doesn't exist")
[28/Jun/2017 16:25:18] "GET /admin/elections/product/ HTTP/1.1" 500 146855
[28/Jun/2017 16:25:23] "GET /admin/ HTTP/1.1" 200 7266
[28/Jun/2017 16:30:24] "POST /accounts/authenticate HTTP/1.1" 302 0
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/ubuntu/workspace/elections/views.py", line 21, in index
    return render(request, 'elections/index.html', context)
  File "/usr/local/lib/python2.7/dist-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/usr/local/lib/python2.7/dist-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/defaulttags.py", line 173, in render
    len_values = len(values)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 232, in __len__
    self._fetch_all()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 1105, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 886, in execute_sql
    raise original_exception
ProgrammingError: (1146, "Table 'c9.elections_product' doesn't exist")
[28/Jun/2017 16:30:25] "GET / HTTP/1.1" 500 137039
Performing system checks...

System check identified no issues (0 silenced).
June 28, 2017 - 16:25:09
Django version 1.11.2, using settings 'database_project.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
Performing system checks...

System check identified no issues (0 silenced).
June 28, 2017 - 16:35:26
Django version 1.11.2, using settings 'database_project.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
Unhandled exception in thread started by <function wrapper at 0x7f9d9dd6eb18>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 227, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/runserver.py", line 117, in inner_run
    autoreload.raise_last_exception()
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 250, in raise_last_exception
    six.reraise(*_exception)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 227, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/ubuntu/workspace/elections/models.py", line 41, in <module>
    class Purchase (models.Model):
  File "/home/ubuntu/workspace/elections/models.py", line 42, in Purchase
    product = models.ForeignKey(Product, on_delete = models.CASCADE)
NameError: name 'Product' is not defined
Unhandled exception in thread started by <function wrapper at 0x7f5e290dfed8>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 227, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/runserver.py", line 117, in inner_run
    autoreload.raise_last_exception()
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 250, in raise_last_exception
    six.reraise(*_exception)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 227, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 116, in populate
    app_config.ready()
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/apps.py", line 23, in ready
    self.module.autodiscover()
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/__init__.py", line 26, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/module_loading.py", line 50, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/ubuntu/workspace/elections/admin.py", line 3, in <module>
    from .models import Product, Poll, Choice
ImportError: cannot import name Product
Unhandled exception in thread started by <function wrapper at 0x7fc44b685ed8>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 227, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/runserver.py", line 117, in inner_run
    autoreload.raise_last_exception()
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 250, in raise_last_exception
    six.reraise(*_exception)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 227, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 116, in populate
    app_config.ready()
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/apps.py", line 23, in ready
    self.module.autodiscover()
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/__init__.py", line 26, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/module_loading.py", line 50, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/ubuntu/workspace/elections/admin.py", line 3, in <module>
    from .models import Product, Poll, Choice
ImportError: cannot import name Product
Unhandled exception in thread started by <function wrapper at 0x7f2031bf79b0>
Performing system checks...

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 227, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/runserver.py", line 125, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/urls.py", line 26, in check_resolver
    return check_method()
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 254, in check
    for pattern in self.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 405, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/ubuntu/workspace/database_project/urls.py", line 19, in <module>
    from elections.views import index
  File "/home/ubuntu/workspace/elections/views.py", line 149
    
    ^
SyntaxError: invalid syntax
/usr/local/lib/python2.7/dist-packages/django/template/defaulttags.py:66: UserWarning: A {% csrf_token %} was used in a template, but the context did not provide the value.  This is usually caused by not using RequestContext.
  "A {% csrf_token %} was used in a template, but the context "
[28/Jun/2017 17:12:28] "GET /accounts/signup HTTP/1.1" 200 1048
[28/Jun/2017 17:12:28] "GET /static/css/bootstrap.css HTTP/1.1" 404 1791
Internal Server Error: /accounts/create
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/ubuntu/workspace/elections/views.py", line 138, in create
    user.save()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 806, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 836, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 903, in _save_table
    forced_update)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 953, in _do_update
    return filtered._update(values) > 0
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 664, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 1191, in execute_sql
    cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 886, in execute_sql
    raise original_exception
ProgrammingError: (1146, "Table 'c9.elections_user' doesn't exist")
[28/Jun/2017 17:12:39] "POST /accounts/create HTTP/1.1" 500 117679
[28/Jun/2017 17:12:43] "GET /static/css/bootstrap.css HTTP/1.1" 404 1791
[28/Jun/2017 17:12:47] "GET /static/css/bootstrap.css HTTP/1.1" 404 1791
[28/Jun/2017 17:28:44] "POST /accounts/authenticate HTTP/1.1" 302 0
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/workspace/home/views.py", line 4, in post_list
    return render(request, 'home/post_list.html', {})
  File "/usr/local/lib/python2.7/dist-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: home/post_list.html
[28/Jun/2017 17:28:45] "GET / HTTP/1.1" 500 89349
Performing system checks...

System check identified no issues (0 silenced).

You have 1 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): elections.
Run 'python manage.py migrate' to apply them.
June 28, 2017 - 17:10:52
Django version 1.11.2, using settings 'database_project.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
[28/Jun/2017 17:29:16] "GET /static/css/bootstrap.css HTTP/1.1" 404 1791
[28/Jun/2017 17:29:18] "POST /accounts/authenticate HTTP/1.1" 302 0
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/ubuntu/workspace/elections/views.py", line 21, in index
    return render(request, 'elections/index.html', context)
  File "/usr/local/lib/python2.7/dist-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/usr/local/lib/python2.7/dist-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/defaulttags.py", line 173, in render
    len_values = len(values)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 232, in __len__
    self._fetch_all()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 1105, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 886, in execute_sql
    raise original_exception
ProgrammingError: (1146, "Table 'c9.elections_product' doesn't exist")
[28/Jun/2017 17:29:19] "GET / HTTP/1.1" 500 136982
[28/Jun/2017 17:31:28] "GET /static/css/bootstrap.css HTTP/1.1" 404 1791
[28/Jun/2017 17:31:30] "POST /accounts/authenticate HTTP/1.1" 302 0
[28/Jun/2017 17:31:31] "GET / HTTP/1.1" 200 799
[28/Jun/2017 17:31:37] "GET /admin/elections/choice/ HTTP/1.1" 200 3056
[28/Jun/2017 17:31:37] "GET /admin/jsi18n/ HTTP/1.1" 200 3217
[28/Jun/2017 17:31:38] "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
[28/Jun/2017 17:31:41] "GET /admin/ HTTP/1.1" 200 7266
[28/Jun/2017 17:31:43] "GET /admin/elections/product/ HTTP/1.1" 200 3063
[28/Jun/2017 17:31:44] "GET /admin/jsi18n/ HTTP/1.1" 200 3217
[28/Jun/2017 17:31:57] "GET /admin/ HTTP/1.1" 200 7266
[28/Jun/2017 17:31:57] "GET /static/admin/img/icon-deletelink.svg HTTP/1.1" 304 0
[28/Jun/2017 17:32:04] "GET /admin/elections/product/ HTTP/1.1" 200 3063
[28/Jun/2017 17:32:06] "GET /admin/ HTTP/1.1" 200 7266
[28/Jun/2017 17:32:07] "GET /admin/logout/ HTTP/1.1" 200 1014
[28/Jun/2017 17:32:09] "GET /admin/ HTTP/1.1" 302 0
[28/Jun/2017 17:32:09] "GET /admin/login/?next=/admin/ HTTP/1.1" 200 1654
[28/Jun/2017 17:32:39] "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
[28/Jun/2017 17:32:40] "GET /admin/ HTTP/1.1" 200 7266
[28/Jun/2017 17:32:44] "GET /admin/elections/choice/add/ HTTP/1.1" 200 6003
[28/Jun/2017 17:32:44] "GET /static/admin/js/change_form.js HTTP/1.1" 304 0
[28/Jun/2017 17:32:45] "GET /admin/jsi18n/ HTTP/1.1" 200 3217
[28/Jun/2017 17:32:45] "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 304 0
[28/Jun/2017 17:32:48] "GET /admin/ HTTP/1.1" 200 7266
[28/Jun/2017 17:32:51] "GET /admin/elections/product/add/ HTTP/1.1" 200 5317
[28/Jun/2017 17:32:51] "GET /admin/jsi18n/ HTTP/1.1" 200 3217
[28/Jun/2017 17:33:21] "POST /admin/elections/product/add/ HTTP/1.1" 302 0
[28/Jun/2017 17:33:21] "GET /admin/elections/product/ HTTP/1.1" 200 4199
[28/Jun/2017 17:33:21] "GET /admin/jsi18n/ HTTP/1.1" 200 3217
[28/Jun/2017 17:33:24] "GET /admin/elections/product/add/ HTTP/1.1" 200 5317
[28/Jun/2017 17:33:24] "GET /admin/jsi18n/ HTTP/1.1" 200 3217
[28/Jun/2017 17:33:46] "POST /admin/elections/product/add/ HTTP/1.1" 302 0
[28/Jun/2017 17:33:46] "GET /admin/elections/product/ HTTP/1.1" 200 4424
[28/Jun/2017 17:33:47] "GET /admin/jsi18n/ HTTP/1.1" 200 3217
[28/Jun/2017 17:33:51] "GET /admin/elections/product/add/ HTTP/1.1" 200 5317
[28/Jun/2017 17:33:52] "GET /admin/jsi18n/ HTTP/1.1" 200 3217
[28/Jun/2017 17:34:19] "POST /admin/elections/product/add/ HTTP/1.1" 302 0
[28/Jun/2017 17:34:19] "GET /admin/elections/product/ HTTP/1.1" 200 4651
[28/Jun/2017 17:34:19] "GET /admin/jsi18n/ HTTP/1.1" 200 3217
[28/Jun/2017 17:34:23] "GET /admin/ HTTP/1.1" 200 7356
[28/Jun/2017 17:34:30] "GET / HTTP/1.1" 200 1498
/usr/local/lib/python2.7/dist-packages/django/db/models/fields/__init__.py:1451: RuntimeWarning: DateTimeField Poll.start_date received a naive datetime (2017-06-28 17:34:36.296914) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python2.7/dist-packages/django/db/models/fields/__init__.py:1451: RuntimeWarning: DateTimeField Poll.end_date received a naive datetime (2017-06-28 17:34:36.296914) while time zone support is active.
  RuntimeWarning)
[28/Jun/2017 17:34:36] "GET /areas/WholeFoodMarket/ HTTP/1.1" 200 578
[28/Jun/2017 17:34:45] "GET /admin/elections/choice/ HTTP/1.1" 200 3056
[28/Jun/2017 17:34:46] "GET /admin/jsi18n/ HTTP/1.1" 200 3217
[28/Jun/2017 17:34:49] "GET /admin/elections/choice/add/ HTTP/1.1" 200 6114
[28/Jun/2017 17:34:49] "GET /admin/jsi18n/ HTTP/1.1" 200 3217
[28/Jun/2017 17:34:53] "GET /admin/elections/choice/ HTTP/1.1" 200 3056
[28/Jun/2017 17:34:54] "GET /admin/ HTTP/1.1" 200 7356
[28/Jun/2017 17:34:56] "GET /admin/elections/poll/ HTTP/1.1" 200 3042
[28/Jun/2017 17:34:57] "GET /admin/jsi18n/ HTTP/1.1" 200 3217
[28/Jun/2017 17:34:59] "GET /admin/elections/poll/add/ HTTP/1.1" 200 5280
[28/Jun/2017 17:34:59] "GET /admin/jsi18n/ HTTP/1.1" 200 3217
[28/Jun/2017 17:35:16] "POST /admin/elections/poll/add/ HTTP/1.1" 302 0
[28/Jun/2017 17:35:16] "GET /admin/elections/poll/ HTTP/1.1" 200 4175
[28/Jun/2017 17:35:16] "GET /admin/jsi18n/ HTTP/1.1" 200 3217
[28/Jun/2017 17:35:18] "GET /admin/ HTTP/1.1" 200 7403
[28/Jun/2017 17:35:20] "GET /admin/elections/choice/ HTTP/1.1" 200 3056
[28/Jun/2017 17:35:20] "GET /admin/jsi18n/ HTTP/1.1" 200 3217
[28/Jun/2017 17:35:22] "GET /admin/ HTTP/1.1" 200 7403
[28/Jun/2017 17:35:24] "GET /admin/elections/product/ HTTP/1.1" 200 4651
[28/Jun/2017 17:35:24] "GET /admin/jsi18n/ HTTP/1.1" 200 3217
[28/Jun/2017 17:35:27] "GET /admin/elections/product/2/change/ HTTP/1.1" 200 5610
[28/Jun/2017 17:35:27] "GET /admin/jsi18n/ HTTP/1.1" 200 3217
[28/Jun/2017 17:35:30] "GET /admin/elections/product/ HTTP/1.1" 200 4651
[28/Jun/2017 17:35:32] "GET /admin/elections/product/1/change/ HTTP/1.1" 200 5603
[28/Jun/2017 17:35:32] "GET /admin/jsi18n/ HTTP/1.1" 200 3217
[28/Jun/2017 17:35:38] "POST /admin/elections/product/1/change/ HTTP/1.1" 302 0
[28/Jun/2017 17:35:38] "GET /admin/elections/product/ HTTP/1.1" 200 4651
[28/Jun/2017 17:35:39] "GET /admin/jsi18n/ HTTP/1.1" 200 3217
[28/Jun/2017 17:35:43] "GET / HTTP/1.1" 200 1524
/usr/local/lib/python2.7/dist-packages/django/template/defaulttags.py:66: UserWarning: A {% csrf_token %} was used in a template, but the context did not provide the value.  This is usually caused by not using RequestContext.
  "A {% csrf_token %} was used in a template, but the context "
[28/Jun/2017 17:35:52] "GET /accounts/login HTTP/1.1" 200 739
[28/Jun/2017 17:35:52] "GET /static/css/bootstrap.css HTTP/1.1" 404 1791
[28/Jun/2017 17:35:54] "GET /accounts/signup HTTP/1.1" 200 1048
[28/Jun/2017 17:35:54] "GET /static/css/bootstrap.css HTTP/1.1" 404 1791
[28/Jun/2017 17:36:10] "POST /accounts/create HTTP/1.1" 302 0
[28/Jun/2017 17:36:10] "GET / HTTP/1.1" 200 1524
/usr/local/lib/python2.7/dist-packages/django/db/models/fields/__init__.py:1451: RuntimeWarning: DateTimeField Poll.start_date received a naive datetime (2017-06-28 17:36:13.438910) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python2.7/dist-packages/django/db/models/fields/__init__.py:1451: RuntimeWarning: DateTimeField Poll.end_date received a naive datetime (2017-06-28 17:36:13.438910) while time zone support is active.
  RuntimeWarning)
[28/Jun/2017 17:36:13] "GET /areas/WholeFoodMarket/ HTTP/1.1" 200 1955
[28/Jun/2017 17:36:16] "POST /polls/1/ HTTP/1.1" 302 0
[28/Jun/2017 17:36:16] "GET /areas/WholeFoodMarket/results HTTP/1.1" 200 968
[28/Jun/2017 17:36:45] "GET /admin/ HTTP/1.1" 302 0
[28/Jun/2017 17:36:46] "GET /admin/login/?next=/admin/ HTTP/1.1" 200 1805
[28/Jun/2017 17:36:49] "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
[28/Jun/2017 17:36:49] "GET /admin/ HTTP/1.1" 200 7450
[28/Jun/2017 17:36:51] "GET /admin/auth/user/ HTTP/1.1" 200 7737
[28/Jun/2017 17:36:51] "GET /admin/jsi18n/ HTTP/1.1" 200 3217
[28/Jun/2017 17:36:51] "GET /static/admin/img/search.svg HTTP/1.1" 304 0
[28/Jun/2017 17:36:51] "GET /static/admin/img/icon-yes.svg HTTP/1.1" 304 0
[28/Jun/2017 17:36:51] "GET /static/admin/img/sorting-icons.svg HTTP/1.1" 304 0
[28/Jun/2017 17:36:51] "GET /static/admin/img/icon-no.svg HTTP/1.1" 200 560
